### ISSUE TITLE
Could you teach me how to setup flake.nix for neovim?

### ISSUE THREAD

**Issue by nyngwang** [Gerg-L/nvim-flake#1]
As title. I use Neovim a lot too(and have built [some](https://github.com/nyngwang/NeoZoom.lua) [plugins](https://github.com/nyngwang/NeoTerm.lua)), but relatively new to Nix. My target is to be able to build Neovim nightly on both macOS and Ubuntu systems without worrying about what dependencies(and their versions) I need to install before building. Came across your dotfiles from the one @the-argus. (unfortunately, both of your configs are a little bit scary to me.)

Could you guide me with the requirements to be able to set up these things? To be clear, my confusions are:

- How do I know what should I put in the `inputs`?
- How do I know what arguments will be passed into a given lambda, e.g. this one: https://github.com/Gerg-L/nvim-flake/blob/b6c8c90b82859297469964f5b54d3df18f7d669f/flake.nix#L27_L29
- How do I know what attributes are required?

Sincerely,
NW.

**Comment by Gerg-L** [comment]
That's basically what flake inputs are, but I don't use them for neovim plugins as nix uses api.github.com and you'll get rate limited very quickly, so I use nvfetcher retrieve all my plugins
