### ISSUE TITLE
Can't seem to install system wide

### ISSUE THREAD

**Issue by RooSoft** [Gerg-L/nvim-flake#138]
First things first, why aren't accollades closed in the example [in the README](https://github.com/Gerg-L/nvim-flake#add-to-user-environment)?

And then, when I try to install this config system wide using the flake, I get random errors alternating from `tl: command not found` to `git: command not found`?

Would love to base my config on yours, as it's working wonderfully with the `nix run` command.

**Comment by Gerg-L** [comment]
> First things first, why aren't accollades closed in the example [in the README](https://github.com/Gerg-L/nvim-flake#add-to-user-environment)?

it looks like github's rendering the page wrong...
look [here](https://github.com/Gerg-L/nvim-flake/blob/master/README.md) it renders correctly for me there

>  I get random errors alternating from tl: command not found to git: command not found?

i don't have `tl` installed anywhere on my system to my knowledge so i'm at a loss with that one.
git however i do have installed so ensure you have git installed systemwide

**Comment by Gerg-L** [comment]
First things first, why aren't accollades closed in the example [in the README](https://github.com/Gerg-L/nvim-flake#add-to-user-environment)?

oops, typo fixing now

    I get random errors alternating from tl: command not found to git: command not found?

i don't have tl installed anywhere on my system to my knowledge so i'm at a loss with that one.
git however i do have installed so ensure you have git installed systemwide

**Comment by RooSoft** [comment]
Seems to be working fine if I remove the `inputs.nixpkgs.follows = "nixpkgs";` in the flake inputs part of my configuration file.

**Comment by RooSoft** [comment]
The README.md looks fine now, thanks a lot for the quick answer!

**Comment by RooSoft** [comment]
What's the purpose of the `follow` line [here](https://github.com/Gerg-L/nvim-flake#flakes)?

Works fine without, and can't compile while there with the above mentioned problems.

**Comment by RooSoft** [comment]
Yes, that might be the problem...

**Comment by Gerg-L** [comment]
Gonna close this, feel free to reopen
